# Configuration minimale de Mosquitto
# On autorise les connexions anonymes pour simplifier le prototype
# En production : authentification par certificat X.509 (tactique Authenticate Actors)

listener 1883
allow_anonymous true